name: Setup node
description: Setup node to run the workflow

inputs:
  node-version:
    description: Node Version (Default LTS)
    required: false
    default: '16'

runs:
  using: "composite"
  steps:
    - name: Node Setup
      uses: syltek/frontend-workflows/setup-node@v0
