name: 'Setup node'
description: 'Set up a common Node version for all the subsequent jobs'

inputs:
  node-version:
    description: 'Node version running in your project (Default LTS)'
    required: false
    default: '16'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
