name: "Send Slack Notification"
description: Send a slack notification for a specific channel

inputs:
  webhook:
    description: "Webhook URL for specific channel"
    required: true
  message:
    description: "Message to send"
    required: false
    default: "Custom message"

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ inputs.webhook }}
        SLACK_MESSAGE: ${{ inputs.message }}
        SLACK_CHANNEL: release-announcements
    # - name: Notify slack
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: ${{ job.status }}
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ inputs.webhook }}
