name: Create release branch (new)

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Enter the new version number"

jobs:
  create_pr:
    name: Create Pull Request
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop
      - name: Make changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch --all
          git merge origin/master --no-commit
          npm version ${{ github.event.inputs.version }} --allow-same-version--no-git-tag-version
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: master
          commit-message: Update branch
          branch: release/v${{ github.event.inputs.version }}
