name: Create release branch (new)

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        required: true
        description: "Release type"
        options:
          - "minor"
          - "hotfix"
          - "major"

jobs:
  check_version:
    name: Create new version
    runs-on: ubuntu-20.04
    outputs:
      current_version: ${{ steps.set_new_version.outputs.current_version }}
      new_version: ${{ steps.set_new_version.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node Setup
        uses: ./.github/actions/setup-node
      - name: Set new version
        id: set_new_version
        shell: bash
        run: |
          ver="$(node -p "require('./package.json').version")"
          release_type="${{ inputs.release_type }}"
          new_ver="$(npx semver -i $release_type $ver)"
          echo "::set-output name=current_version::$ver"
          echo "::set-output name=new_version::$new_ver"
      - name: Finish process
        run: |
          echo "### Success ✅" >> $GITHUB_STEP_SUMMARY
          echo "Release type: ${{ inputs.release_type }}" >> $GITHUB_STEP_SUMMARY
          echo "Given the current version (${{ steps.set_new_version.outputs.current_version }}), the new version candidate for the release is ${{ steps.set_new_version.outputs.new_version }}" >> $GITHUB_STEP_SUMMARY
  create_pr:
    needs: [check_version]
    name: Create Pull Request
    runs-on: ubuntu-20.04
    outputs:
      pull_request_url: ${{ steps.create_pull_request.outputs.pull-request-url }}
      pull_request_operation: ${{ steps.create_pull_request.outputs.pull-request-operation }}
      translation_token: ${{ secrets.MY_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_PAT }}
      - name: Configure Git credentials
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Update branch with master (minor/major)
        if: ${{ inputs.release_type != 'hotfix' }}
        id: update_branch
        run: |
          git checkout develop
          git merge origin/master
          git checkout master
          git reset --hard develop
        continue-on-error: true
      - run: |
          echo "${{ steps.update_branch.outcome }}"
      - name: Check merge failures
        if: ${{ (steps.update_branch.outcome != 'success') && ( steps.update_branch.outcome != 'skipped' ) }}
        run: |
          echo "### Failure ❌" >> $GITHUB_STEP_SUMMARY
          echo "### There was an error during the merge process. This usually means that the destination branch is ahead and cannot be fast-forwarded. Please try again or run the process manually instead" >> $GITHUB_STEP_SUMMARY
          exit 1
      - name: Upgrade version
        run: |
          npm version ${{ needs.check_version.outputs.new_version }} --allow-same-version
      - name: Create Pull Request
        id: create_pull_request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.MY_PAT }}
          title: "Release v${{ needs.check_version.outputs.new_version }}"
          base: ${{ env.GITHUB_REF }}
          branch: release/v${{ needs.check_version.outputs.new_version }}
          body: v${{ needs.check_version.outputs.new_version }}
          assignees: ${{ github.actor }}
          labels: |
            release
            automated
            v${{ needs.check_version.outputs.new_version }}
            ${{ inputs.release_type }}
        continue-on-error: true
      - name: Check merge failures
        if: ${{ steps.create_pull_request.outcome != 'success' }}
        run: |
          echo "### Failure ❌" >> $GITHUB_STEP_SUMMARY
          echo "### There was an error during the Pull Request creation. Please try again or run the process manually instead" >> $GITHUB_STEP_SUMMARY
          exit 1
  update_translations:
    name: Update Translations
    needs: [check_version, create_pr]
    uses: ./.github/workflows/update-translations.yml
    with:
      release_token: "${{ needs.create_pr.outputs.translation_token }}"
      change_type: "commit"
      branch: "release/v${{ needs.check_version.outputs.new_version }}"
  finish_process:
    name: Finish process
    needs: [check_version, create_pr, update_translations]
    runs-on: ubuntu-20.04
    steps:
      - name: Finish Pull Request (Created)
        if: ${{ needs.create_pr.outputs.pull_request_url && needs.create_pr.outputs.pull_request_operation == 'created' }}
        run: |
          echo "### Success ✅" >> $GITHUB_STEP_SUMMARY
          echo "The Pull Request has been created and the translations have been updated" >> $GITHUB_STEP_SUMMARY
          echo "Pull Request - ${{ needs.create_pr.outputs.pull_request_url }}" >> $GITHUB_STEP_SUMMARY
      - name: Finish Pull Request (Updated)
        if: ${{ needs.create_pr.outputs.pull_request_url && needs.create_pr.outputs.pull_request_operation == 'updated' }}
        run: |
          echo "### Success ✅" >> $GITHUB_STEP_SUMMARY
          echo "The Pull Request already exists and has been updated as well as the translations" >> $GITHUB_STEP_SUMMARY
          echo "Pull Request - ${{ needs.create_pr.outputs.pull_request_url }}" >> $GITHUB_STEP_SUMMARY
