name: Deploy and commit

on:
  workflow_dispatch:
  push:
    branches:
      - "develop"

jobs:
  build:
    name: Create new version
    runs-on: ubuntu-latest

    steps:
      - name: Setup-Node
        uses: actions/setup-node@v3
        with:
          node-version: 10
          cache: 'npm'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Get version
        id: get_version
        shell: bash
        run: |
          branch="${{ github.base_ref }}"
          sha="${GITHUB_SHA}"
          ver="$(node -p "require('./package.json').version")"
          echo "::set-output name=version::$ver-$branch-$sha"
