name: Deployment Pipeline

on:
  pull_request:

jobs:
  cancel_ongoing_flows:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous ongoing build
        uses: styfle/cancel-workflow-action@main
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
