name: Deployment Pipeline

on:
  pull_request:

jobs:
  cancel_ongoing_flows:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel previous ongoing build
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.MY_PAT }}
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "14"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
