name: Synchronize Master with Develop after merge

# Make sure this is only when a PR is merged from a release branch
on:
  push:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node Setup
        uses: ./.github/actions/setup-node
      - name: Create sync branch
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git fetch --all
          git checkout -B sync-master-develop origin/develop
          git merge origin/master
          git push --force origin sync-master-develop
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '[CI/CD] Sync master with develop',
              owner,
              repo,
              head: 'sync-master-develop',
              base: 'develop',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['sync', 'automated']
            });
