name: Update translations
on:
  workflow_dispatch:
    inputs:
      change_type:
        description: Change type
        type: choice
        default: "pull_request"
        required: true
        options:
          - pull_request
          - commit
  workflow_call:
    inputs:
      change_type:
        description: Change type
        type: string
        default: "commit"
        required: false
      branch:
        description: Branch name
        type: string
        default: "master"
        required: false
      called_from_wf:
        description: Flag to know whether this is called from a workflow
        type: boolean
        default: true
        required: false

jobs:
  update-translations:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}
      - name: Use Node 14
        uses: ./.github/actions/setup-node
      - name: Print event
        if: ${{ inputs.called_from_wf }}
        run: |
          echo "${{ github.event_name }}"
      - name: Commit changes
        shell: bash
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          echo "Added another line to README.md" >> ./RELEASE.md
          git add ./RELEASE.md
          git commit -m "chore(translations): update translations"
      - name: Create pull-requests
        if: ${{ inputs.change_type == 'pull_request' }}
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          base: ${{ env.GITHUB_REF }}
          branch: ci/update-translations
          # PR related options
          title: 📘 Update translations
          body: |
            Updated translations for [playtomic-admin](https://app.phrase.com/accounts/syltek-solutions-s-l/projects/playtomic-admin/dashboard)
            > Triggered by @${{ github.actor }}
          labels: |
            automated-pr
            translations
          reviewers: ${{ github.actor	}}
          delete-branch: true
      - name: Push changes
        if: ${{ inputs.change_type == 'commit' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ inputs.branch }}
